# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:08
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import suites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, max_length=100, populate_from=b'name', unique=True)),
                ('about', models.TextField()),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('private', models.BooleanField(default=False)),
                ('featured', models.DateTimeField(blank=True, null=True)),
                ('hashed_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('tag_list', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-modified', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SuiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to=suites.models.suite_images_file_name)),
                ('image_large', models.ImageField(blank=True, null=True, upload_to=b'suite_images/large')),
                ('image_large_blur', models.ImageField(blank=True, null=True, upload_to=b'suite_images/large_blur')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to=b'suite_images/small')),
                ('top_position', models.IntegerField(default=0)),
                ('left_position', models.IntegerField(default=0)),
                ('scale', models.FloatField(default=1.0)),
                ('caption', models.CharField(blank=True, max_length=512)),
                ('credit', models.CharField(blank=True, max_length=512)),
                ('credit_link', models.CharField(blank=True, max_length=512)),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='suites.Suite')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suite_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuiteInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email_invite', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name=b'invite email address')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[(b'pending', b'pending'), (b'accepted', b'accepted'), (b'rejected', b'rejected')], default=b'pending', max_length=20)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='suites.Suite')),
                ('user_invited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL)),
                ('user_inviting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SuiteMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[(b'normal', b'normal'), (b'editor', b'editor'), (b'owner', b'owner'), (b'blocked', b'blocked')], default=b'normal', max_length=20)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='suites.Suite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_suites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SuitePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(blank=True, default=b'', max_length=140)),
                ('object_id', models.PositiveIntegerField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suite_posts_added', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_posts', to='suites.Suite')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SuiteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[(b'pending', b'pending'), (b'accepted', b'accepted'), (b'rejected', b'rejected')], default=b'pending', max_length=20)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_requests', to='suites.Suite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SuiteStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('featured', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default=b'', max_length=140)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suite_stories_added', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_suites', to='articles.Article')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_stories', to='suites.Suite')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='suite',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suite_hero', to='suites.SuiteImage'),
        ),
        migrations.AddField(
            model_name='suite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_suites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='suiterequest',
            unique_together=set([('suite', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='suitemember',
            unique_together=set([('suite', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='suiteinvite',
            unique_together=set([('user_inviting', 'user_invited', 'suite', 'email')]),
        ),
    ]
