# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('link', models.URLField(blank=True, default=b'', max_length=512)),
                ('hashed_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('tag_list', models.TextField(blank=True)),
                ('oembed_string', models.TextField(blank=True)),
                ('status', models.CharField(choices=[(b'draft', b'draft'), (b'published', b'published'), (b'deleted', b'deleted')], db_index=True, default=b'published', max_length=20)),
                ('media_type', models.CharField(choices=[(b'general', b'general'), (b'media', b'media'), (b'photo', b'photo'), (b'tweet', b'tweet'), (b'instagram', b'instagram'), (b'unknown', b'unknown')], db_index=True, default=b'unknown', max_length=20)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LinkProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default=b'', max_length=512)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[(b'ok', b'ok'), (b'banned', b'banned'), (b'unknown', b'unknown')], db_index=True, default=b'unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LinkProviderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to=b'link_providers/image')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_images', to='links.LinkProvider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='linkprovider',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_image', to='links.LinkProviderImage'),
        ),
        migrations.AddField(
            model_name='link',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_links', to='links.LinkProvider'),
        ),
    ]
