DEFAULT_PAGE_SIZE = 15

# Search Objects
SEARCH_TYPE_STORY = 1
SEARCH_TYPE_SUITE = 2
SEARCH_TYPE_USER = 3
SEARCH_TYPE_LINK = 4
SEARCH_TYPE_SUPPORT = 5

# Min body length for indexing
MIN_ARTICLE_CHAR_LENGTH = 2000

# EPOCH date for new articles feed
SUITE_EPOCH = '2013-12-01'
SUITE_MIGRATION_EPOCH = '2014-04-01'
EPOCH_ID = 207000

# CONSIDERED CURRENT IF PUBLISHED WITHIN...
CURRENT_RANGE = 90 

STORY_LENGTH_INDEX_THRESHOLD = 200

SUITE_STORY_THRESHOLD = 2
INDEX_STORY_COUNT_THRESHOLD = 2

# Privacy settings
PRIVACY_NOBODY = 0
PRIVACY_FOLLOWERS = 1
PRIVACY_ANYBODY = 2

HERO_IMAGE_LARGE_WIDTH = 1600
HERO_IMAGE_SMALL_WIDTH = 600
HERO_IMAGE_BLUR_RADIUS = 40

ARTICLE_IMAGE_LARGE_WIDTH = 1200
ARTICLE_IMAGE_COLUMN_WIDTH = 876
ARTICLE_IMAGE_MAX_SMALL_WIDTH = 250

PROFILE_IMAGE_MAX_WIDTH = 200
PROFILE_IMAGE_MAX_THUMB_WIDTH = 50
ARTICLE_IMAGE_MAX_WIDTH = 648
ARTICLE_IMAGE_MAX_THUMB_WIDTH = 250
JPEG_IMAGE_QUALITY = 90

DEFAULT_HEX_COLOR = '#313a3f'

HASH_TYPE_USER = 1
HASH_TYPE_STORY = 2 # archived story
HASH_TYPE_SUITE = 3
HASH_TYPE_CONVERSATION = 4
HASH_TYPE_LINK = 5
HASH_TYPE_POST = 6
HASH_TYPE_UNKNOWN = 13



