# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('private', models.BooleanField(default=True)),
                ('hashed_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('last_post_date', models.DateTimeField(db_index=True, null=True)),
                ('title', models.CharField(blank=True, default=b'', max_length=500)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='ConversationInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to='conversations.Conversation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[(b'active', b'active'), (b'moderator', b'moderator'), (b'blocked', b'blocked')], default=b'active', max_length=20)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='conversations.Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('posted_on', models.DateTimeField(db_index=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', model_utils.fields.SplitField(blank=True, no_excerpt_field=True)),
                ('word_count', models.IntegerField(default=0)),
                ('story_dup', models.BooleanField(default=False)),
                ('original_source', models.URLField(blank=True, verbose_name=b'Source')),
                ('alchemy_entity_str', models.TextField(blank=True)),
                ('alchemy_keyword_str', models.TextField(blank=True)),
                ('entity_list', models.TextField(blank=True)),
                ('keyword_list', models.TextField(blank=True)),
                ('tag_list', models.TextField(blank=True)),
                ('status', models.CharField(choices=[(b'draft', b'draft'), (b'published', b'published'), (b'deleted', b'deleted')], db_index=True, default=b'draft', max_length=20)),
                ('hashed_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('_body_excerpt', models.TextField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='conversations.Post')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_conversations', to='conversations.Post'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together=set([('conversation', 'user')]),
        ),
    ]
