# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20160421_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conv_posts', to='conversations.Conversation'),
        ),
    ]
