# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_postrecommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postrecommend',
            old_name='author',
            new_name='user',
        ),
    ]
