# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_postembed'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archive_pk',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
