# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_conversation_archive_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
